### ISSUE TITLE
complete activity 04

### ISSUE THREAD

**Issue by lonebots** [lonebots/ros#34]
## Task 
Goal 🥇  : 
- [ ] Create a battery node
- [ ] Create a led panel node 
- [ ] Create custom message for publishing battery state
- [ ] Create custom service type for setting led state via request/response
----------------------------------------------

**Conditions**
1. The LED panel consist of 3 LED s with `initial_state : [0 ,0, 0]` this needs to be published to `/led_state` topic by the `led_panel` node, it also act as a server with the service `set_led` used to change the LED states to `ON` or `OFF`
2. The client node `batter_node` sends request to the service based on the battery status
- **state 1** : `full battery` then set `led_state : [0, 0, 0]` (turn **OFF** all the LED s)
- **state 2** : `empty battery` then set `led_state : [0, 0, 1]` (turn **ON** the last LED s)

alternate the battery state between `FULL` and `EMPTY` using timer or loop indefinitely it takes 4 second to drain the battery empty and 6s to fully charge it again.
